# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/sublimearts/sublimestripe/models/singlecharge/columns.yaml

# Model Class name
modelClass: SublimeArts\SublimeStripe\Models\SingleCharge

# List Title
title: Manage Single Charges

# Link URL for each record
recordUrl: sublimearts/sublimestripe/singlecharges/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Filter widget configuration
filter: config_filter.yaml

# Default sorting column
defaultSort:
    column: created_at
    direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
